---
# This file would normally be encrypted with ansible-vault:
#   ansible-vault encrypt vault/secrets.yml
# and then included with: vars_files: [ vault/secrets.yml ]
#
# In CI, decrypt at runtime with:
#   ansible-playbook ... --vault-password-file ~/.vault_pass
#
# DO NOT commit a real vault password file.

vault_snmp_ro:        "REPLACE_ME_RO_COMMUNITY"
vault_netadmin_secret: "$1$REPLACE_ME$REPLACE_ME_HASH"
